### ISSUE TITLE
The different ways we name things

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#604]
Different words are used for similar things. Here are some examples:

### x axis

- .`align-center`
- `.btn--pill-hc` _pill horizontal center_ which I think should be removed in favour of `unround`
- `flex-parent--center-main`
- Spacing utils (i.e. `px12`)
- `.mx-auto`

### y axis

- `align-middle`
- `.flex-parent--center-cross`
- Spacing utils (i.e. `py12`)

### Other positions

- single letter (i.e. `.round-t`)
- spelt out `.top`, `.right`, `.bottom`, `.left`
- `.triangle--u`, `.triangle--d`

---

We should standardize more so there's a system in place for remembering. My vote: 

- Refer to axis in short-form `x`, `y`
- Refer to positions in short-form `t`, `r`, `b`, `l`
- Spell out `center` instead of a short-form `c`

**Comment by samanpwbb** [comment]
I agree with the basic idea behind your three final bullet points. Have some clarifying questions / comments:

- Should `align-middle` should be renamed to `align-x`? I don't think so. 
- Is it weird that our `text-align` and `vertical-align` classes use the same naming pattern?
- Should `mx-auto` should be renamed? I don't think so.
- Should triangle classes be renamed? I would find `t`, `b` triangle modifiers ambiguous. What's a "top" or "bottom" triangle? An "up" or "down" triangle makes sense to me.

**Comment by davidtheclark** [comment]
This is a little bit confusing, because you are naming a lot of things but not actually proposing we change very much, right?

- Ok, so you want to change `btn--pill-hc` to `btn--pill-hcenter`, right? I guess that seems fine.
- Positions are already referred to with the short-forms. Except `.top`, etc., which we deliberately chose not to abbreviate into one-letter classes.
- Axes are already referred to as `x` and `y`. The `cross` and `main` axes on flexbox are different things so need different words. `cross` is the `y` axis by default but becomes the `x` axis when you have `flex-parent--column`.

To @samanpwbb's points:

- I don't think `align-middle` is the same as `align-y` (which is what you meant, right?). `vertical-align: middle` has weird behaviors, so I think it makes sense for the class to directly correspond to the value you are setting.
- I do think it's a little weird that we text-align and vertical-align classes use the same pattern. Everybody wanted just `align-`! But I'd be happy with switching to two groups, `text-align-*` and `vertical-align-*`.
- Why would we rename `mx-auto`? To make the name more function-based? Like, `horizontally-center-block-with-set-width`?
- For triangles, since they are not l-t-r-b, I would be in favor of expanding the existing names: `triangle--upward`, `triangle--downward`, `triangle--leftward`, `triangle--rightward`?

**Comment by samanpwbb** [comment]
I agree with all your points @davidtheclark – i wasn't suggesting renaming any of the things i brought up. 

What are the concrete changes being proposed here? I only see:

- rename `btn--pill-hc` to `btn--pill-hcenter`. Okay, this seems like a reasonable change.
- rename triangles to `triangle--upward`, `triangle--downward`, `triangle--leftward`, `triangle--rightward`? I vote no. -u, -d seem fine.
- Break out the `align` rules into `text-align-*` and `vertical-align-*`. I vote no. What we have now is easy to remember and good IMO.

**Comment by davidtheclark** [comment]
@tristen What are you thinking on this issue? Let's take some action or close it?

**Comment by tristen** [comment]
Let's just close this. I was collecting a list of things that kind of relate with slight name variation and I thought seeing them in one place might help to make them more uniform. Looks like there isn't really.
