### ISSUE TITLE
Renaming the flex classes

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#672]
When addressing https://github.com/mapbox/assembly/issues/648  I realized I used `flex-parent flex-parent--center-main` on the modal close button to perfectly center the icon along the x and y axis. I'm actually doing the same in the _input with spinner_ example:

```html
<div class='relative'>
  <div class='absolute top right flex-parent flex-parent--center-cross flex-parent--center-main w36 h36'>
    <span class='loading loading--s' />
  </div>
  <input class='input pr36' placeholder='Search'>
</div>
```

Which I think is pretty reasonable but there's a bit to unpack in those classes. `flex-parent flex-parent--center-cross flex-parent--center-main` are hard to understand. 

I'd think we should change the names to the following:

- `flex-parent` 👉 `flex`.  
This aligns with how we represent the other display properties `absolute`, `static`, `relative` ... 
- `flex-parent-inline` 👉 `flex-inline`.  
the value is actually _`inline-flex`_ but I think that's more confusing.
- `flex-parent--center-main` 👉 `flex--center-x`
- `flex-parent--center-cross` 👉 `flex--center-y`  
adding `flex--center-x` flex--center-y` centers children along the x and y axis.
- `.flex-parent--end-cross` 👉 `.flex--align-bottom`  
I don't think we need to know this concerns the y axis. We are just naturally aligning the children from the bottom up.
- `.flex-parent--end-main` 👉 `.flex--align-right`
I don't think we need to know this concerns the x axis. We are just naturally aligning the children from the right of the parent.
- `.flex-parent--stretch-cross` 👉 `flex--stretch-y`

---

Related: doesn't `.flex-parent--column` seem weird? It sets the direction of the axis from top to bottom. But I think of it as ordering children as rows on a grid as opposed to columns. Like I would never think of this as the shape of the parent (a column). I'm adding that class because I want the children to be ordered as rows and not columns.

**Comment by davidtheclark** [comment]
@tristen I think you have two suggestions here:

- Don't use `flex-parent`.
- Use x/y instead of main/cross (top/bottom/left/right = x/y).

Why not use `flex-parent`? Is something confusing about that? It pairs nicely with `flex-child`, and distinguishes the two. You want `flex`/`flex-child` instead of `flex-parent`/`flex-child`? I think that this distinction is more important than `flex` being aligned with `inline`, `absolute`, and other `display` properties.

As we've discussed in chat, changing main/cross to x/y doesn't seem to me like a good idea because it's inaccurate. `flex-parent--column` changes the orientation, changes the effect of those classes. And we *do* use `flex-parent--column` — e.g. in app-style columns where one of the rows is internally scrolling. 

`flex-parent--column` is a modifier of the flex parent, saying that the flex parent is a column instead of a row. That doesn't seem so problematic to me.

I don't think it's so much to ask that people who use the flexbox classes learn a couple of things about flexbox. After all, if they do not know what they're during they might get unintended effects, no matter how we name the classes.

**Comment by tristen** [comment]
> As we've discussed in chat, changing main/cross to x/y doesn't seem to me like a good idea because it's inaccurate. `flex-parent--column` changes the orientation, changes the effect of those classes. And we *do* use `flex-parent--column` — e.g. in app-style columns where one of the rows is internally scrolling. 

In cases like this, I wish we weren't so married to the single class principle. I'd much rather favour easier to remember and work with. So if `flex--column` is also on the parent container then `flex--center-y` would change (to what `flex-parent--center-main` is currently).

> You want `flex`/`flex-child` instead of `flex-parent`/`flex-child` 

Yes. I think it's weird that it's different from our other display classes and I don't think we should be that tied to the parent -> child relationship. At least with the built-in Assembly components that have child classes dependent on a parent we call it `-container` and not parent. I'm also writing them a bunch so cutting out `-parent` would be nice for longer class lists.

**Comment by samanpwbb** [comment]
> In cases like this, I wish we weren't so married to the single class principle. I'd much rather favour easier to remember and work with. So if flex--column is also on the parent container then flex--center-y would change (to what flex-parent--center-main is currently).

Your suggestion goes against the grain of how flexbox wants you to think about layout. Flexbox is designed so that you can switch the primary axis of content. This is useful when adjusting layouts based on breakpoints.

> Yes. I think it's weird that it's different from our other display classes

`flex` is fundamentally very different from other display types. Setting `display:flex` is the same as setting `display:block` on an element. The difference is how `display:flex` effects it's children.

**Comment by tristen** [comment]
You both disagree with me.
