### ISSUE TITLE
More complete flexbox support

### ISSUE THREAD

**Issue by kronick** [mapbox/assembly#744]
I love that Assembly includes support for `flexbox`! It makes it feel grounded in really future-thinking design principles. Unfortunately I find myself needing to write custom CSS using the `flexbox` classes directly to get the most out of it.

Two things that I've come across that are missing in Assembly:
- `justify-content: space-between` is really useful for making navigation bars that group some items to the left and some to the right. It's way more predictable than `float: left` and `float: right` for this task! (`justify-content: space-around` is useful as well)
- The `order` property on flexbox is especially useful for responsive layouts-- for example a sidebar layout that you want to change into a bottom-bar layout on mobile. Assembly supports switching the parent from `flex-direction: column` to `flex-direction: row`, but not re-ordering items when the layout changes. Yes, for two items you can achieve this with `flex-direction: column-reverse` but for more complex layouts being able to specify the order in a way that's similar to the `.z0`-`.z5` classes would be great.

**Comment by davidtheclark** [comment]
@kronick There's the potential for us to add a flex class corresponding to *every flexbox property-value combination*. We started with some commonly useful classes; have since added a few more; and you're right that other some flexbox property-values are indeed useful. 

A quick word on why these are useful, as opposed to using inline CSS (e.g. `<div style="flex-justify: space-between">`):
- Vendor-prefixing is a big deal for flexbox.
- Media-query variants are a big deal for any layout classes.

If I understand right, you're proposing the following new classes:

- `flex-parent--space-between-main`: 👍 
- maybe `flex-parent--space-around-main`: not so sure about this one — I'm having trouble envisioning a layout design in which we'd want to use it. I bet @samanpwbb hates the idea, right?
- `flex-child--order1`, `flex-child--order2`, etc.: 👍 — but how high do we need to go? Up to 5?

**If we're going to add these classes, are there any other flex classes we should add?** I've considered adding classes for *all* the non-shorthand property-values — but some of those property-values really don't seem like good ideas for well designed components. Then again, I'm probably too quick to judge that I won't want something down the line.

**Comment by samanpwbb** [comment]
We should definitely ease into flexbox rather than dive in head first.  Add things when we realize we need them.

Yes: `flex-parent--space-between-main`.
Skeptical: `-space-around` – results in layouts that have left and right margins. Not good. 
Somewhat skeptical, but open to the idea of: flex-child--order1, flex-child--order2, etc. – I think these would be especially useful if there are responsive variants.

**Comment by tristen** [comment]
I might be misunderstanding the use case but I don't think we should introduce space-between properties. We have [grid & gutter classes](https://www.mapbox.com/assembly/documentation/#Grid) that employ a negative margin technique so space between columns fits perfectly within the grid.

**Comment by tristen** [comment]
Ahh @samanpwbb enlightened me that `flex-parent--space-between-main` is great for header content where a logo and nav items should be flanked on either side of a container. This is a good addition to have.

**Comment by kronick** [comment]
Thanks for considering this! Here's a snippet showing what I would do with `flex-child--order-n` classes, showing a common sidebar layout that becomes a bottom-bar layout on small screens:
```
<div class='flex flex-parent flex-parent--column flex-parent-row-ml'>
    <div class='flex-child flex-child--order-2 flex-child--order-1-ml h360 w-full h-full-ml w360-ml flex-child--no-shrink'>
        Fixed width sidebar on big screens, fixed height bottom bar on small screens
    </div>
    <div class='flex-child flex-child--order-1 flex-child--order-2-ml flex-child--grow'>
        Main content
    </div>
</div>
```

Having `order` classes from 1-5 would probably be good enough for doing layouts-- in my experience I've used `order` mostly to make one thing show up first/last (similar to using `z-index` to get things on top of/behind everything else) rather than doing detailed ordering in CSS.

Here's a snippet showing a use of a `space-between` class for a header with elements that are pinned left and right:

```
<div id='header' class='flex flex-child flex-parent flex-parent--space-between-main'>
    <div>Pinned left</div>
    <div>Pinned right</div>
</div>
```

`flex-parent--space-around-main` does result in left/right margins, and could be useful for some layouts of gridded content (i.e. a grid of image thumbnails) but is, in my opinion, less useful than `space-between`. I don't think I'd miss it too much.

**Comment by tristen** [comment]
@kronick your first example can be achieved by using `flex-parent--row-reverse`. I'm somewhat skeptical we need order because > 2 things are common enough?

**Comment by kronick** [comment]
@tristen You're right-- and if you think adding the order classes would only add clutter, I could live without them. But I do think it parallels nicely with the `.z0`-`.z5` classes

**Comment by davidtheclark** [comment]
In #756 (for next release) I added `flex-parent--space-between-main`. So let's decide if this issue should be closed, or we should add the `*--order1`+ classes. I've never found the need for them myself ... sounds like @tristen and @samanpwbb haven't yet, either, and @kronick hasn't yet *needed* them in a way that we couldn't handle with other classes, right? Should we close, then, and come back to this possibility if we come to feel a more urgent desire?

**Comment by kronick** [comment]
@davidtheclark Cool- thanks for working in `flex-parent--space-between-main`! I'm happy with closing this now; if anyone needs `order` classes down the road we can re-open.
