### ISSUE TITLE
Redesign select inputs

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#747]
One piece of feedback @katydecorah brought up when we reviewed Assembly was the frustrating lack of 1px stroked variations of buttons. Should we add these? I think if there's a straightforward way that doesn't add much weight or complexity to the stylesheet, we should.

**Comment by davidtheclark** [comment]
My personal inclination is to make stroke selects look like inputs (1px border) rather than buttons, so I'm in favor.

**Comment by katydecorah** [comment]
After thinking about my initial feedback, I have a suggestion regarding just the `.select` class.

I've noticed that select is the only form element that is filled with a color (blue) as a default. The filled default often competes with buttons and at the same time can never feel consistent with inputs or textareas because they do not have fill classes. To stay consistent with the other elements, I think we should change `.select`:

* `.select` should be a 1px gray outline with a white background - matching the default styling of `.input` and `.textarea`.

![image](https://cloud.githubusercontent.com/assets/2180540/23614811/3afce29e-0252-11e7-88de-aba96bbea995.png)

If we like this change, then I don't think we need to change `select--stroke` or add a 1px variation.

**Comment by davidtheclark** [comment]
@katydecorah: I'm in favor. I share the same suspicion about our selects looking like buttons. Also, if we styled our selects like inputs, that would also solve one part of the color variant problem (#746).

**Comment by samanpwbb** [comment]
I'm open to this change – I see the benefit of dropdowns that don't look like buttons. What would the hover state look like?

**Comment by katydecorah** [comment]
> What would the hover state look like?

We could darken the border on hover which would make the hover state consistent with radios and checkboxes.

**Comment by samanpwbb** [comment]
closed by #787
