### ISSUE TITLE
tile-layout example needs to be reworked

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#764]
In this example are a lot of violations of some important patterns. We should rework it.

I'll try to get to this soon, just don't have the time at this very moment so wanted to create an issue.

**Comment by davidtheclark** [comment]
I fiddled with this a bit and came out a little disappointed. It's very complex to implement this specific layout *without* (height-percentage classes (besides 100%) and *with* obedience to the patterns that we have documented. 

I wonder if we should simplify the example. @tristen what do you think?

**Comment by davidtheclark** [comment]
Addendum to ^^: I might propose height-percentage classes ... but I think that aspect of this tile-layout example might be too contrived, without real-world applicability.

**Comment by tristen** [comment]
Can you talk me through what's bothering you about this? I can think of a couple:

1. It's using `grid` & `grid--gut12` in a confusing way.
2. It's not keeping to a pattern of using `flex-child` on elements that just descend from a parent.  

I think it should be straightforward to address ^ and otherwise I think this is a good example to have and I don't see why we would introduce percentage based heights. The wrapper that contains the elements introduces the height (or doesn't) and flex containers _flex_ to meet the y space.

**Comment by davidtheclark** [comment]
Yeah, I'll try to be specific, sorry.

- I actually wasn't confused by the use of grid and the gutter. Should I have been?
- You're right that we need the `flex-child`. I've spotted some IE bugs (leading to #762) that suggest that the `flex-child` class probably is important after all.
- `col col--12` should not be used only to get full width. I think the use of `.col12` in base to get full width was a confusing practice that came out of the lack of a `w-full` class, right? I don't think we should perpetuate it.
- Overall, it's just very difficult and confusing, I think, even if it does work. If you can pull it off with the ^^ fixes, then great, in one way. But it's super clever, so doesn't really illustrate the common use-cases for these classes. Or maybe it does and I'm being daft. The use of `flex-parent--wrap`, for example, throws me for a loop. I think that if you tried to use this example to learn about the grid and flexbox, you would come away very confused and frustrated!

**Comment by tristen** [comment]
> I actually wasn't confused by the use of grid and the gutter. Should I have been?

Maybe it's fine actually :P It's just that it's being used for one gutter while other 12px spacing uses a combination of padding or margin 12px rules:

<img width="1062" alt="screen shot 2017-03-20 at 9 31 33 am" src="https://cloud.githubusercontent.com/assets/61150/24101943/8cd31f4e-0d50-11e7-93c4-f54b115adb68.png">

I could probably take out that gutter rule and keep uniform with a margin class for that one column. But it would require another wrapping element so it's probably not worth it.

---

Maybe I can take a crack at simplifying the logic to this? instead of `flex-parent--wrap` I can probably use row or column orientation on the parent and use a stretch class for the children?

**Comment by tristen** [comment]
🔪 #988
