### ISSUE TITLE
Adding a search field

### ISSUE THREAD

**Issue by kepta** [mapbox/assembly#774]
Currently the only way I know to search the documentation is to do a `ctrl + f` and hope that I get what I am looking for. :(

Is it possible to add a global search for all the documentation ?

**Comment by davidtheclark** [comment]
How would a search field end up *better* than `ctrl + f`?

**Comment by kepta** [comment]
@davidtheclark, it doesn't bring much to the table. 
But ya two relatively minor issues which could possibly be fixed with an indexed search:
- User gets an assurance what he/she is searching is actually a definition/doc and not a usage info of some other property. For example, if I am searching using `ctrl + f` for `bg` the first thing I get is a `prose--dark` doc not a `bg` doc. 
- If I am in `examples` sub-section, I can't search for documentation and vice versa.

**Comment by davidtheclark** [comment]
If anyone is interested in doing this, I suggest looking into Algolia, which we could use for free because the project is open source.

**Comment by samanpwbb** [comment]
My take on this issue is _pretty_ similar to David's – if we are going to invest more energy in Assembly's site, I would prefer if we prioritized other work above this. A single-page documentation site makes ctrl+f very usable – there are more important things for us to focus on if we want to improve the website, like [adding more tutorials](https://github.com/mapbox/assembly/issues/772)!

**Comment by samanpwbb** [comment]
ctrl+f works!
