### ISSUE TITLE
Add screen size variation classes to limiter

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#942]
Sometimes you want page content to be full-screen unless viewed on a larger viewport `-mxl` where a limiter should be in place. It would be nice to have ` limiter--mxl` class to do that.

**Comment by tristen** [comment]
👋 I changed the intent of the referenced PR to "_Deprecate limiter_" [based on discussions here](https://github.com/mapbox/assembly/pull/949#pullrequestreview-623746089) and I'd like some input (particularly @katydecorah from a docs perspective) on the plan I have:

1. **Drop `limiter`**. Compose classes instead.
2. **Drop `col` modifier classes: `col--{n}`, `col--offl{n}`, `col--offr{n}`**. These classes provide percentage-based width or margin-left, margin-right values and are a) better spent as general-purpose layout selectors and b) decouples their relationship to just benefitting flex layouts.
3. **Introduce fractional layout classes** Like `w-1/3`, `ml-11/12`. to replace the requirements of col modifiers.
4. **Expand `wmax{n}`** to include larger pixel-based values. 

Doing this means the following ❌ breaking changes:

1. For parity, `limiter` would need to change over to something like `w-full px24 w-11/12-mm mx-auto-mm px0-mm w-11/12-ml wmax1200-mm` 
2. `col--{n}`, `col--offl{n}`, `col--offr{n}` classes would require updates to their renamed counterpart.

---

Another point worth discussing in a separate ticket is how our `grid` classes currently work. They present a problem when layout rules are applied to children - i.e you need to use `grid` and `grid--gut12` selectors on the parent to apply spacing on children. Adding layout rules to grid children can lead to the grid layout breaking. 

The plan above breaks the rule that you should not add layout classes to children. Instead, we would modify this to be _you can only apply percentage-based layout classes to children_. This either needs to be documented more concretely or we could explore swapping out CSS flex for CSS grids which might provide more benefit (i.e you can explicitly set `row-gap` and `column-gap` in CSS grids

**Comment by katydecorah** [comment]
> Drop limiter. Compose classes instead.

👍  We override `limiter` on larger screens for our own wider version. I think your proposed changes will allow use to replace our custom wide limiter for these new classes.

> Drop col modifier classes: col--{n}, col--offl{n}, col--offr{n}.
> Introduce fractional layout classes

👍 I think fractional layout classes will be great! I've had trouble working with `col--` when building layouts since I never felt like I could get the right granularity with the breakpoints (columns felt to wide then suddenly too small at some breakpoint points). For our `PageLayout`, we use a mix of `flex` and `grid` classes, which works well for our layout and will be improved by the ability to use, I think.

The docs team mostly uses `col--` for small components layouts like setting cards or images in a (responsive) row and from what I can tell, fractional layout classes will allow us to still do that.

> Expand wmax{n} to include larger pixel-based values.

👍  The docs team is be interested in `wmax1800` or something in that range.

> Another point worth discussing in a separate ticket is how our grid classes currently work. 

I'm not sure if I have too much to add here, yet. But in case, it's helpful I built out a skeleton of our PageLayout to show how we're using `grid` and `flex` classes:

- Pink outline = `flex` classes
- Blue outline = `grid` classes
- Light blue outline = `col` classes

<img width="1214" alt="Screen Shot 2021-04-01 at 10 33 36 AM" src="https://user-images.githubusercontent.com/2180540/113310015-beb2a480-92d5-11eb-8159-079ad78ba6fd.png">

https://codepen.io/katydecorah/pen/a11699ff9bbbc67b2fd06ff633e44c0c

**Comment by samanpwbb** [comment]
https://github.com/mapbox/assembly/pull/949
