### ISSUE TITLE
*-faint colors also not available for buttons

### ISSUE THREAD

**Issue by thefifthisa** [mapbox/assembly#945]
According to the [documentation](https://labs.mapbox.com/assembly/documentation/#Buttons), `*-dark` colors aren't available for buttons, but it seems `*-faint` colors [aren't valid color variants either](https://github.com/mapbox/assembly/blob/80ffe8bb2b55447a121792c30da8eb444e32c5b4/scripts/build-color-variants.js#L86). (They default to [blue](https://github.com/mapbox/assembly/blob/80ffe8bb2b55447a121792c30da8eb444e32c5b4/src/variables.json#L65) if used.) The `buildColorVariants` function or docs should be updated in this case.

**Comment by samanpwbb** [comment]
@thefifthisa check out https://github.com/mapbox/assembly/blob/publisher-staging/scripts/build-color-variants.js#L71-L93 for code that builds button variants. We intentionally exclude faint because they're too low contrast. Now, I can see a good argument _against_ doing this: you want to use faint buttons against a dark background. For that reason, we could consider expanding the button color rules.

There's a workaround in the meantime: use something like `bg-blue-faint color-blue-faint bg-blue-light-on-hover color-blue-light-on-hover`.

**Comment by samanpwbb** [comment]
Going to close this and add `wontfix` label. Open to proposals for how to refactor color variants to allow dark text on light backgrounds in a separate issue.
