### ISSUE TITLE
Refresh commonly used icons

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#966]
Assembly’s icons have served us well, but we need to touch them up. Two big reasons for the refresh 1) most of them were designed for non-retina screens and can look unpolished on modern displays (sharp edges, thick strokes, ect), and 2) the icons don’t have consistent visual weight. Here are the icons we should target, because they're most heavily used:

- close
- lock/unlock
- eye/noeye
- mountain
- pencil
- plus 
- undo/redo
- search
- share
- sprocket
- sun
- trash

@katydecorah do you have any requests from docs?

**Comment by katydecorah** [comment]
@samanpwbb Two come to mind:

- code (it’s wider than other icons so sometimes it feels off next to others, but given the content it may need to be.)
- lightning (it seems to lose definition at smaller sizes)

In case it's helpful, here are the icons we use in Dr UI:

- alert
- arrow-{down|left|right|up}
- book
- bookmark
- check
- chevron-{down|right|up}
- close
- code
- creditcard
- github
- lightning
- plus
- search
- share

**Comment by tristen** [comment]
Without really considering any priority, (and ignoring the headline of this ticket) here are some thoughts:

### Requests!

- `pitch`, `pan` - icons that represent this behaviour
- `camera`
- `boolean`
- `zoom`
- `3d`
- `eyedropper`
- `plug`
- `terminal`

### Improve

- The scale of `sun` and `moon` feel small
- Icons like `map` and `globe` could feel more harmonious with one another
- `join-round` feels too large
- `star` is too sharp
- Strong visual harmony between icons used for vector/raster

### Drop 🔪 

- `lifebuoy`
- `tooltip`
- `circle`

Less relevant third party icons that should be one-offs on pages instead of available in Assembly:

- `wechat`
- `slack`
- `qt`
